name: zano # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: "Zano coin: official wallet. Secure. Scalable. Easy to Use."
description: |
  Zano is a scalable and secure coin, designed for use in e-commerce.
  The technology behind our blockchain provides reliability, security,
  and flexibility — a perfect option for P2P transactions.
  More info: http://zano.org
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  libboost:
    plugin: dump
    source: .

    override-pull: |
      curl https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2 -OL &&\
      echo '7f6130bc3cf65f56a618888ce9d5ea704fa10b462be126ad053e80e553d6d8b7 boost_1_68_0.tar.bz2' | sha256sum -c - &&\
      pwd && echo pulled ok

    override-build: |
      tar -xjf $SNAPCRAFT_PART_SRC/boost_1_68_0.tar.bz2
      cd boost_1_68_0
      pwd
      ./bootstrap.sh --with-libraries=system,filesystem,thread,date_time,chrono,regex,serialization,atomic,program_options,locale,timer
      ./b2
      mkdir -p $SNAPCRAFT_PART_INSTALL/boost_1_68_0 $SNAPCRAFT_PART_INSTALL/boost_1_68_0/stage
      cp -pr boost     $SNAPCRAFT_PART_INSTALL/boost_1_68_0/
      cp -pr stage/lib $SNAPCRAFT_PART_INSTALL/boost_1_68_0/stage/

    build-packages:
      - curl
      - build-essential
      - g++
      - libicu-dev

    stage-packages:
      - libicu60
      
  zano-bin:
    after: [ libboost ]
    source: https://github.com/hyle-team/zano.git
    plugin: cmake

    override-build: |
      cmake -DBOOST_ROOT=$SNAPCRAFT_STAGE/boost_1_68_0 -DBOOST_LIBRARYDIR=$SNAPCRAFT_STAGE/boost_1_68_0/stage/lib -DSTATIC=True $SNAPCRAFT_PART_SRC
      make -j1 daemon simplewallet      
      cp src/zanod $SNAPCRAFT_PART_INSTALL
      cp src/simplewallet $SNAPCRAFT_PART_INSTALL
      
    build-packages:
      - build-essential
      - g++
      - libicu-dev


apps:
  zano:
    command: zanod
